LOGIN     = "adeboose"
SERVER_IP = "192.168.56.110"
BOX       = "bento/debian-13"

Vagrant.configure("2") do |config|
  config.vm.box = BOX
  config.vm.boot_timeout = 900

  #============================Server VM==============================
  config.vm.define "#{LOGIN}S" do |control|
    control.vm.hostname = "#{LOGIN}S"
    control.vm.network "private_network", ip: SERVER_IP

    control.vm.provider "virtualbox" do |v|
      v.name = "#{LOGIN}S"
      v.memory = 2048
      v.cpus = 2
      v.gui = false
      v.customize ["modifyvm", :id, "--paravirtprovider", "kvm"]
    end

    control.vm.provider "vmware_desktop" do |v|
      v.vmx["displayname"] = "#{LOGIN}S"
      v.memory = 2048
      v.cpus = 2
      v.gui = false
    end
    control.vm.provision "shell", path: "scripts/install_k3s.sh", args: [SERVER_IP]
  end
end
