LOGIN     = "adeboose"
SERVER_IP = "192.168.56.110"
BOX       = "bento/ubuntu-26.04"

Vagrant.configure("2") do |config|
  config.vm.box = BOX

  #============================Server VM==============================
  config.vm.define "#{LOGIN}S" do |control|
    control.vm.hostname = "#{LOGIN}S"
    control.vm.network "private_network", ip: SERVER_IP

    control.vm.provider "vmware_desktop" do |v|
      v.vmx["displayname"] = "#{LOGIN}S"
      v.memory = 1024
      v.cpus = 1
      v.gui = false
    end
    control.vm.provision "shell", path: "scripts/install_k3s.sh", args: [SERVER_IP]
  end
end
